### ISSUE TITLE
Afspraak maken met Frank de Jooden

### ISSUE THREAD

**Issue by Lennnardk** [studata-platform/studata-frontend#4]
Voor informatie over bedrijven en eventuele samenwerking met het semester Data Science.

**Comment by leroykorterink** [comment]
Frank heeft nog niet gereageerd op onze mail.

**Comment by Lennnardk** [comment]
> Frank heeft nog niet gereageerd op onze mail.

Bedankt voor deze aanvulling Leroy!!!1
